version: '3.8'
services:
  db:
    image: postgres:15
    container_name: testetecnico-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TesteTecnicoDb
      TZ: "Brazil/East"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: motorcycle-system-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_ENVIRONMENT: Development 
      ConnectionStrings__DefaultConnection: "Host=db;Database=TesteTecnicoDb;Username=postgres;Password=postgres"

volumes:
  db_data:
